doc/urls.py
from django.urls import path
from . import views
from . import response

urlpatterns = [
    path('pdf2docx', views.pdf2docx, name='pdf2docx'),
    path('csv2excel', views.csv2excel, name='csv2excel'),
    path('excel2csv', views.excel2csv, name='excel2csv'),
    path('pdf2image', views.pdf2image, name='pdf2image'),
    path('mergepdf', views.merge_pdf, name='mergepdf'),

    path('pdf2docx/<str:id>/', response.download_docx, name='download-docx'),
    path('csv2excel/<str:id>/', response.download_excel, name='download-excel'),
    path('excel2csv/<str:id>/', response.download_csv, name='download-csv'),
    path('pdf2image/<str:id>/', response.download_image, name='download-images'),
    path('mergepdf/<str:id>/', response.download_pdf, name='download-merged-pdf'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('doc/', include('doc.urls')),
    path('tts/', include('tts.urls')),
    path('img/', include('img.urls')),
    path('video/', include('video.urls')),
]

video/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('videomerge', views.videomerge, name="videomerge"),
    path('video-to-audio', views.video_to_audio, name="video2audio"),

    path('download/video/<str:id>/', views.download_video, name='download-video'),
    path('download/audio/<str:id>/', views.download_audio, name='download-audio'),
    path('preview/<str:id>/', views.preview_video, name='preview-video'),
]

video/models.py
from django.db import models
import uuid

def file_rename(instance, filename):
    ext = filename.split('.')[-1]
    return f'video/temp/{instance.id}.{ext}'

class convertedVideo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=True)
    video = models.FileField(upload_to=file_rename)
    audio = models.FileField(upload_to=file_rename)
    output_video = models.FileField(upload_to='video')

    def __str__(self):
        return str(self.id)

class videoToAudio(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=True)
    video = models.FileField(upload_to=file_rename)
    audio = models.FileField(upload_to='video/audio')

    def __str__(self):
        return str(self.id)

video/views.py
import os
from uuid import uuid4
from django.core.files import File
from django.http import HttpResponse
from django.shortcuts import render
from .func import convert_video, extract_audio
from .models import convertedVideo, videoToAudio

vid_ext = ['mp4', 'mov', 'wmv', 'avi', 'mkv']
aud_ext = ['mp3', 'aac', 'ogg', 'wav']


def videomerge(request):
    if request.method == 'POST' and request.FILES:
        video = request.FILES['video']
        audio = request.FILES['audio']
        if video.name[-3:] not in vid_ext and audio.name[-3:] not in aud_ext:
            return render(request, 'video/videomerge.html', {'message': True})

        id = str(uuid4())
        convertedVideo(id=id, video=video, audio=audio).save()

        obj = convertedVideo.objects.get(id=id)
        try:
            url = convert_video(obj.video.url[1:], obj.audio.url[1:])
            with url.open(mode='rb') as f:
                obj.output_video = File(f, f'{id}.mp4')
                obj.video.delete()
                obj.audio.delete()
                obj.save()
            os.remove(url)
        except:
            obj.video.delete()
            obj.audio.delete()
            obj.save()
            obj.delete()
            return render(request, 'video/videomerge.html', {'error': True})

        return render(request, 'video/videomerge.html', {'data': obj})

    return render(request, 'video/videomerge.html')


def download_video(request, id):
    obj = convertedVideo.objects.get(id=id)

    fl_path = obj.output_video.url[1:]
    filename = 'converted_video.mp4'

    fl = open(fl_path, 'rb')
    response = HttpResponse(fl, content_type='video/mp4')
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response


def download_audio(request, id):
    obj = videoToAudio.objects.get(id=id)

    fl_path = obj.audio.url[1:]
    filename = 'converted_audio.mp3'

    fl = open(fl_path, 'rb')
    response = HttpResponse(fl, content_type='audio/mp3')
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response


def preview_video(request, id):
    obj = convertedVideo.objects.get(id=id)
    return render(request, 'video/preview.html', {'data': obj})


def video_to_audio(request):
    if request.method == 'POST' and request.FILES:
        video = request.FILES['video']
        if video.name[-3:] not in vid_ext:
            return render(request, 'video/video_to_audio.html', {'message': True})

        id = str(uuid4())
        videoToAudio(id=id, video=video).save()

        obj = videoToAudio.objects.get(id=id)
        url = extract_audio(obj.video.url[1:])
        with open(url, 'rb') as f:
            obj.audio = File(f, f'{id}.mp3')
            obj.video.delete()
            obj.save()

        os.remove(url)
        return render(request, 'video/video_to_audio.html', {'data': obj})

    return render(request, 'video/video_to_audio.html')

templates/video/preview.html
{% extends "base.html" %}

{% block title %}
Preview
{% endblock %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Merge Video and Audio</h1>
  <hr class="my-4">
  <h2 class="text-center">Preview of The Video...</h2>
<center>
<video width="400" height="300" controls controlsList="nodownload">
  <source src="{{ data.output_video.url }}" type="video/mp4">
</video>
</center>
{% endblock %}

templates/video/video_to_audio.html
{% extends "base.html" %}

{% block title %}
Extract Audio From Video
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Extract Audio From Video</h1>
    <p class="lead text-center">Upload the video, and download the audio file converted from it.. </p>
    <hr class="my-4">

    <div class="row">
        <div class="col-sm">
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row mt-4 mb-4 pl-4 pr-4">
                    <div class="col">
                        <p>
                            <label for="id_video">Upload Video:</label>
                            <input type="file" name="video" required id="id_video">
                        </p>
                    </div>
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary btn-lg btn-block mt-3">Extract</button>
                    </div>
                </div>
            </form><br>
        </div>
        <div class="col-sm mt-4 mb-4 pl-4 pr-4">
            {% if data %}
            <p class="text-left">Your request has been processed.... </p><br>
            <p>Download Audio:
                <a class="btn btn-outline-primary" href={% url 'download-audio' id=data.id %}
                    role="button">Download</a>
            </p>
            {% endif %}
        </div>
    </div>

    {% if message %}
    <div class="alert alert-warning" role="alert">
        <p>Invalid File Format, only '.mp4' video files are Supported..</p>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/video/videomerge.html
{% extends "base.html" %}

{% block title %}
Merge Video and Audio
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Merge Video and Audio</h1>
    <p class="lead text-center">Upload the video and audio file, it'll merge both the files and give it to you..</p>
    <hr class="my-4">

    <div class="row">
        <div class="col-sm">
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row mt-4 mb-4 pl-4 pr-4">
                    <div class="col">
                        <p>
                            <label for="id_video">Upload Video : </label>
                            <input type="file" name="video" required id="id_video">
                        </p>
                        <p>
                            <label for="id_audio">Upload Audio : </label>
                            <input type="file" name="audio" required id="id_audio">
                        </p>
                    </div>
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary btn-lg btn-block mt-3">Merge</button>
                    </div>
                </div>
            </form><br>
        </div>
        <div class="col-sm mt-4 mb-4 pl-4 pr-4">
            {% if data %}
            <p class="text-left">Your request has been processed.... </p><br>
            <p class="text-left">Preview Video:
                <a class="btn btn-outline-secondary" href={% url 'preview-video' id=data.id %} role="button"
                    target="_blank">Preview</a>
            </p><br>

            <p>OR Download Video:
                <a class="btn btn-outline-primary" href={% url 'download-video' id=data.id %} role="button">Download</a>
            </p>
            {% endif %}
        </div>
    </div>


    {% if error %}
    <div class="alert alert-warning" role="alert">
        <p>Internal Server Error, Sorry For inconvenience you faced. Please Try again. </p>
    </div>
    {% endif %}

    {% if message %}
    <div class="alert alert-warning" role="alert">
        <p>Invalid File Format, only '.mp4' videos and '.mp3' audio files are Supported..</p>
    </div>
    {% endif %}
</div>
{% endblock %}